language: node_js
branches:
  only:
  - master
node_js:
  - "node"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn build
after_success:
 - cd dist/
 - git init .
 - git config --global user.email "travis@travis-ci.org"
 - git config --global user.name "Travis"
 - git remote add origin https://${GH_TOKEN}@github.com/agendaopensource/agendaopensource.github.io.git
 - git checkout -b master
 - git add --all -f .
 - git commit -a -m "Travis - ${TRAVIS_BUILD_NUMBER}"
 - git push --force origin master
