version: '3'
services:
  agenda:
    build:
      context: ./
      args:
        UID: ${UID-1000}
        NODE_ENV: development
    volumes:
      - ./:/usr/src/app
    #env_file:
    #  - .env
    ports:
      - "3000:3000"
      - "9229:9229"
    command: yarn start
